/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-01-30 01:37:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.demo.testpaper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addNounTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/tld/general.tld", Long.valueOf(1538117498787L));
    _jspx_dependants.put("/WEB-INF/jsp/demo/public/menu.jsp", Long.valueOf(1547547908992L));
    _jspx_dependants.put("/static/common/taglibs.jsp", Long.valueOf(1541399470113L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1532604868850L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/jsp/demo/public/headCssJs.jsp", Long.valueOf(1545295123769L));
    _jspx_dependants.put("/WEB-INF/jsp/demo/public/pageTop.jsp", Long.valueOf(1542961855154L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>添加名词测试</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap-switch.css\"  rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/currency.css\">\r\n");
      out.write("    <link href=\"/static/css/pcdiRequired.css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/font-awesome/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/toastr/toastr.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/gritter/jquery.gritter.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/dataTables/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/dataTables/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/dataTables/dataTables.tableTools.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/datapicker/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap-switch.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/metisMenu/jquery.metisMenu.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/inspinia.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/slimscroll/jquery.slimscroll.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/pace/pace.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-ui-1.10.4.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-migrate-1.1.0.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/dataTables.bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/dataTables.responsive.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/dataTables.tableTools.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/datapicker/Moment.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/datapicker/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/jsTree/jstree.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/chosen/chosen.jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/layer/layer.js\"></script>\r\n");
      out.write("    <!-- 页面的js列表 -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sha1.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.ajaxfileupload.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    function switchChange(data){\r\n");
      out.write("\r\n");
      out.write("        alert(data);\r\n");
      out.write("    }\r\n");
      out.write("    function getSwitch(data,id){\r\n");
      out.write("        var ret=\"\";\r\n");
      out.write("        if(data==0){\r\n");
      out.write("            ret='<div class=\"switch switch-mini\" id=\"switchId\" >'+'<input  value=\"0\" rowId='+id+' type=\"checkbox\" checked />'+'</div>';\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        if(data==1){\r\n");
      out.write("            ret='<div class=\"switch switch-mini\" id=\"switchId\" >'+'<input value=\"1\" rowId='+id+' type=\"checkbox\" />'+'</div>';\r\n");
      out.write("        }\r\n");
      out.write("        return ret;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /**\r\n");
      out.write("     * 时间戳转日期\r\n");
      out.write("     * @param timestamp\r\n");
      out.write("     * @returns {*}\r\n");
      out.write("     */\r\n");
      out.write("    function timestampToTime(timestamp) {\r\n");
      out.write("        var date = new Date(timestamp * 1000);//时间戳为10位需*1000，时间戳为13位的话不需乘1000\r\n");
      out.write("        Y = date.getFullYear() + '-';\r\n");
      out.write("        M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';\r\n");
      out.write("        D = date.getDate() + ' ';\r\n");
      out.write("        h = date.getHours() + ':';\r\n");
      out.write("        m = date.getMinutes() + ':';\r\n");
      out.write("        s = date.getSeconds();\r\n");
      out.write("        if(s < 10){\r\n");
      out.write("            s = \"0\"+s;\r\n");
      out.write("        }\r\n");
      out.write("        return Y+M+D+h+m+s;\r\n");
      out.write("    }\r\n");
      out.write("    /**\r\n");
      out.write("     * 时间戳转日期\r\n");
      out.write("     * @param timestamp\r\n");
      out.write("     * @returns {*}\r\n");
      out.write("     */\r\n");
      out.write("    function timestampToyyyy_MM_dd(timestamp) {\r\n");
      out.write("        var date = new Date(timestamp * 1000);//时间戳为10位需*1000，时间戳为13位的话不需乘1000\r\n");
      out.write("        Y = date.getFullYear() + '-';\r\n");
      out.write("        M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';\r\n");
      out.write("        D = date.getDate() + ' ';\r\n");
      out.write("        return Y+M+D;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .firstLevelMenu{\r\n");
      out.write("        font-size: medium;\r\n");
      out.write("    }\r\n");
      out.write("   #side-menu li{\r\n");
      out.write("        display: none;\r\n");
      out.write("        color: red;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("    <nav class=\"navbar-default navbar-static-side\" role=\"navigation\">\r\n");
      out.write("        <div class=\"sidebar-collapse\">\r\n");
      out.write("            <ul  class=\"nav metismenu\" id=\"side-menu1\">\r\n");
      out.write("                <li class=\"nav-header\">\r\n");
      out.write("                    <div class=\"dropdown profile-element\"> <span>\r\n");
      out.write("                            <img alt=\"image\" class=\"img-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/page/baidumarker.png\"/>\r\n");
      out.write("                             </span>\r\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                            <span class=\"clear\"> <span class=\"block m-t-xs\"> <strong class=\"font-bold\">管理人员</strong>\r\n");
      out.write("                             </span>  </span> </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"logo-element\">\r\n");
      out.write("                        <input  hidden id=\"thisUserid\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.get(\"user\").id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav metismenu\" id=\"side-menu\">\r\n");
      out.write("                <li id=\"workbench_menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >工作台</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"workbenchmenu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/workbench/toWorkBenchPage\">工作台</a></li>\r\n");
      out.write("                        <li id=\"workbenchmenu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/trainTest/toCoursewaretListPage\">课件统计</a></li>\r\n");
      out.write("                        <li id=\"workbenchmenu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/trainTest/touserDetailList\">用户详情统计</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"image_Menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >图片管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"image_manage_Menu\"><a href=\"\">名词图片管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNoumTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNoumTestPage\">测试</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNounSensePage\">意义</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li id=\"image_manage_Menu11\"><a href=\"\">动词图片管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/verb/toVerbTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu4\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/verb/toVerbTestPage\">测试</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li id=\"image_manage_Menu12\"><a href=\"\">句子成组管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu5\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceGroupTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu6\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceGroupTestPage\">测试</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li id=\"image_manage_Menu13\"><a href=\"\">句子分解管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu7\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceResolveTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu8\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceResolveTestPage\">测试</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"msq_Menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >问卷管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"msq_Menu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toPcdiList\">pcdi必做问卷</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toPcdiSelectList\">pcdi选做问卷</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toAbcListPage\">ABC问卷</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/topcdiAndabc/resultPage\">问卷记录</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu4\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toWordListPage\">建议设置</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"user_menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >人员管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"user_menu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/getAccountList\">账号管理</a></li>\r\n");
      out.write("                        <li id=\"user_menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roleAccess/toRoleListPage\">角色管理</a></li>\r\n");
      out.write("                        <li id=\"user_menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/user/toParentsPage\">用户管理</a></li>\r\n");
      out.write("                        <li id=\"user_menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/user/toChildPage\">儿童管理</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"system_menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >系统管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"system_menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toVersionPage\">版本日志</a></li>\r\n");
      out.write("                        <li id=\"system_menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toStrartPage\">启动页</a></li>\r\n");
      out.write("                        <li id=\"system_menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toIntroduceList\">产品介绍</a></li>\r\n");
      out.write("                        <li id=\"system_menu4\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toSuggestPage\">信息设置</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function (){\r\n");
      out.write("        var  id= $(\"#thisUserid\").val();\r\n");
      out.write("       var AccessList = '';\r\n");
      out.write("        //获取该用户的权限\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/getUserAccessList\",\r\n");
      out.write("            data:{id:id},\r\n");
      out.write("            dataType: 'JSON',\r\n");
      out.write("            type:\"POST\",\r\n");
      out.write("            success: function (result) {\r\n");
      out.write("                console.log(result);\r\n");
      out.write("                if (result.code == 200) {\r\n");
      out.write("                    var list = result.data;\r\n");
      out.write("                    for(var i = 0; i< list.length; i++){\r\n");
      out.write("                        if (list[i].access != null){\r\n");
      out.write("                            $(\"#\"+list[i].access).css(\"display\",\"block\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }else {\r\n");
      out.write("                    alert(result.msg);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // init vConsole\r\n");
      out.write("   /* var vConsole = new VConsole();\r\n");
      out.write("    console.log('Hello world');*/\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper animated fadeInRight gray-bg\">\r\n");
      out.write("    <div class=\"row border-bottom\">\r\n");
      out.write("        <nav class=\"navbar navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a id=\"user\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/toindexPage\">\r\n");
      out.write("                        <input  hidden id=\"accountId\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.get(\"user\").id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        <i class=\"fa fa-user\" ></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.get(\"user\").accountName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a id=\"updatePassword\">\r\n");
      out.write("                        <i class=\"fa fa-key\" ></i>修改密码\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/loginOut\">\r\n");
      out.write("                        <i class=\"fa fa-sign-out\"></i> 退出\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"exampleModalLabel\">修改密码</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"control-label\">旧密码:</label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"oldPassword\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label  class=\"control-label\">新密码:</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"newPassword1\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label  class=\"control-label\">确认密码:</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"newPassword2\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-success\" id=\"updatePasswordBtn\">确定</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(\"#updatePassword\").click(function () {\r\n");
      out.write("        $(\"#exampleModal\").modal('show');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("        $(\"#updatePasswordBtn\").click(function(){\r\n");
      out.write("            var oldPassword=$(\"#oldPassword\").val();\r\n");
      out.write("            var newPassword1=$(\"#newPassword1\").val();\r\n");
      out.write("            var newPassword2 =$(\"#newPassword2\").val();\r\n");
      out.write("            if(oldPassword==\"\"||oldPassword==null||oldPassword==\"undefined\"){\r\n");
      out.write("            alert(\"请填写旧密码！\");\r\n");
      out.write("            return;\r\n");
      out.write("            }\r\n");
      out.write("            if(newPassword1==\"\"||newPassword1==null||newPassword1==\"undefined\"){\r\n");
      out.write("                alert(\"请填写新密码！\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if(newPassword2==\"\"||newPassword2==null||newPassword2==\"undefined\"){\r\n");
      out.write("                alert(\"请填写确认密码！\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if(newPassword1 != newPassword2){\r\n");
      out.write("                alert(\"新密码和确认密码不相同！\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/updatePassword\",\r\n");
      out.write("                type: 'POST',\r\n");
      out.write("                dataType:'json',\r\n");
      out.write("                data: {\r\n");
      out.write("                    \"oldPassword\":oldPassword,\r\n");
      out.write("                    \"newPassword\":newPassword1,\r\n");
      out.write("                    \"accountId\":$(\"#accountId\").val()\r\n");
      out.write("                },\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("                    console.log(data);\r\n");
      out.write("                    if (data.code == 200) {\r\n");
      out.write("                        $(\"#exampleModal\").modal('hide');\r\n");
      out.write("                        alert(data.msg);\r\n");
      out.write("                        window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/loginOut\";\r\n");
      out.write("                    }else{\r\n");
      out.write("                        alert(data.msg);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"page-wrapper\" class=\"gray-bg\">\r\n");
      out.write("        <div class=\"wrapper wrapper-content animated fadeInRight\">\r\n");
      out.write("            <form class=\"form-horizontal\" id=\"carouselFigure_form\">\r\n");
      out.write("                <legend>名词管理>>添加/编辑名词测试\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" style=\"margin-left: 20px;\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </legend>\r\n");
      out.write("                <div class=\"form-group\" id=\"imgDiv\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label textColor\">卡一颜色图:</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"sc\">\r\n");
      out.write("                                <img class=\"img-result img\" id=\"img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardColorImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"160px\"\r\n");
      out.write("                                     height=\"165px\"/>\r\n");
      out.write("                                <input name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input class=\"file\" type=\"file\" name=\"cardOneImage\"\r\n");
      out.write("                                   accept=\"image/gif, image/png, image/jpeg, image/bmp, image/jpg\" id=\"cardOneImage\"\r\n");
      out.write("                                   onchange=\"uploadHouseFile(this.id,'img')\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">卡一形容词</label>\r\n");
      out.write("                    <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"卡一形容词\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardColorChar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"cardColorChar\"\r\n");
      out.write("                               class=\"form-control\" id=\"cardColorChar\" style=\"width:300px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label textColor\">卡一录音:</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            <input class=\"file\" accept=\"audio/*\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardColorRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"file\" name=\"cardOneRecord\"\r\n");
      out.write("                                   id=\"cardOneRecord\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\" id=\"imgDiv2\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label textColor\">卡二线框图:</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"sc\">\r\n");
      out.write("                                <img class=\"img-result img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardWireImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"img2\" width=\"160px\"\r\n");
      out.write("                                     height=\"165px\"/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input class=\"file\" type=\"file\" name=\"cardTwoImage\"\r\n");
      out.write("                                   accept=\"image/gif, image/png, image/jpeg, image/bmp, image/jpg\" id=\"cardTwoImage\"\r\n");
      out.write("                                   onchange=\"uploadHouseFile(this.id,'img2')\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">卡二名词</label>\r\n");
      out.write("                    <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"卡二名词\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardWireChar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"cardWireChar\"\r\n");
      out.write("                               class=\"form-control\" id=\"cardWireChar\" style=\"width:300px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label textColor\">卡二文字录音:</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            <input class=\"file\" accept=\"audio/*\" type=\"file\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardWireRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"cardTwoRecord\"\r\n");
      out.write("                                   id=\"cardTwoRecord\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\" id=\"imgDiv3\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label textColor\">组合图片:</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"sc\">\r\n");
      out.write("                                <img class=\"img-result img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.groupImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"img4\" width=\"160px\"\r\n");
      out.write("                                     height=\"165px\"/>\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input class=\"file\" type=\"file\" name=\"groupImage\"\r\n");
      out.write("                                   accept=\"image/gif, image/png, image/jpeg, image/bmp, image/jpg\" id=\"groupImage\"\r\n");
      out.write("                                   onchange=\"uploadHouseFile(this.id,'img4')\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">组合文字</label>\r\n");
      out.write("                    <div class=\"col-sm-10\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"组合文字\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.groupChar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"groupChar\"\r\n");
      out.write("                               class=\"form-control\" id=\"groupChar\" style=\"width:300px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label textColor\">组合录音:</label>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            <input class=\"file\" accept=\"audio/*\" type=\"file\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.groupRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"groupRecord\"\r\n");
      out.write("                                   id=\"groupRecord\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">辅助时长1:</label>\r\n");
      out.write("                    <div class=\"col-sm-4\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"f1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.fristAssistTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"f2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.secondAssistTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <select style=\"width: 100px\" name=\"fristAssistTime\" id=\"fristAssistTime\">\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"col-sm-2 control-label\">辅助时长2:</label>\r\n");
      out.write("                    <div class=\"col-sm-4\">\r\n");
      out.write("                        <select style=\"width: 100px\" name=\"secondAssistTime\" id=\"secondAssistTime\">\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group pull-left\" style=\"margin-left:110px;\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" id=\"btn-ok\">确认添加</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" id=\"btn-cancel\">取消</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        var f1 = $(\"#f1\").val()\r\n");
      out.write("        var f2 = $(\"#f2\").val()\r\n");
      out.write("        for (var i = 0; i < 61; i++) {\r\n");
      out.write("            if (f1 == i) {\r\n");
      out.write("                $(\"#fristAssistTime\").append(\"<option selected=\\\"selected\\\" value=\\\"\"+f1+\"\\\">\" + f1 + \"</option>\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#fristAssistTime\").append(\" <option  value='\" + i + \"'>\" + i + \"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (f2 == i) {\r\n");
      out.write("                $(\"#secondAssistTime\").append(\"<option selected=\\\"selected\\\" value=\\\"\"+f1+\"\\\">\" + f2 + \"</option>\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#secondAssistTime\").append(\" <option  value='\" + i + \"'>\" + i + \"</option>\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //取消按钮\r\n");
      out.write("        $(\"#btn-cancel\").click(function () {\r\n");
      out.write("            window.history.go(-1);\r\n");
      out.write("        });\r\n");
      out.write("        //确定按钮\r\n");
      out.write("        $(\"#btn-ok\").click(function () {\r\n");
      out.write("            var formData = new FormData($('#carouselFigure_form')[0]);\r\n");
      out.write("            var id = $(\"#id\").val()\r\n");
      out.write("            var url = \"\"\r\n");
      out.write("            if (id == null || id == \"\") {\r\n");
      out.write("                url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/addNounTest\"\r\n");
      out.write("            } else {\r\n");
      out.write("                url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/updateNounTest\"\r\n");
      out.write("            }\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: url,\r\n");
      out.write("                type: 'POST',\r\n");
      out.write("                dataType: 'json',\r\n");
      out.write("                data: formData,\r\n");
      out.write("                processData: false,  // 不处理数据\r\n");
      out.write("                contentType: false,  // 不设置内容类型\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("                    if (response.code == \"200\") {\r\n");
      out.write("                        alert(\"添加成功！\")\r\n");
      out.write("                        window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNoumTestPage\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(response.msg)\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                fail: function (e) {\r\n");
      out.write("                    console.log(e)\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    //图片预览\r\n");
      out.write("    function getFileUrl(sourceId) {\r\n");
      out.write("        var url;\r\n");
      out.write("        if (window.ActiveXObject || \"ActiveXObject\" in window) { // IE\r\n");
      out.write("            url = document.getElementById(sourceId).value;\r\n");
      out.write("        } else if (navigator.userAgent.indexOf(\"Firefox\") > 0) { // Firefox\r\n");
      out.write("            url = window.URL.createObjectURL(document.getElementById(sourceId).files.item(0));\r\n");
      out.write("        } else if (navigator.userAgent.indexOf(\"Chrome\") > 0) { // Chrome\r\n");
      out.write("            url = window.URL.createObjectURL(document.getElementById(sourceId).files.item(0));\r\n");
      out.write("        }\r\n");
      out.write("        return url;\r\n");
      out.write("    }\r\n");
      out.write("    function uploadHouseFile(sourceId, targetId) {\r\n");
      out.write("        var url = getFileUrl(sourceId);\r\n");
      out.write("        var imgPre = document.getElementById(targetId);\r\n");
      out.write("        if (imgFormat(sourceId)) {\r\n");
      out.write("            imgPre.src = url;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    //图片格式校验\r\n");
      out.write("    function imgFormat(nodeId) {\r\n");
      out.write("        if ($(\"#\" + nodeId).val() != \"\") {\r\n");
      out.write("            var imgFileName = \"jpg,png,jpeg\";\r\n");
      out.write("            var imgName = $(\"#\" + nodeId).val();\r\n");
      out.write("            if (imgFileName.indexOf(imgName.substring(imgName.lastIndexOf(\".\") + 1, imgName.length).toLowerCase()) != -1) {\r\n");
      out.write("                return true;\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"只支持格式为\" + imgFileName + \"的图片！\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        } else if ($(\"input[name='license']\").val() != \"\" || $(\"input[name='shopLogo']\").val() != \"\"\r\n");
      out.write("            || $(\"input[name='shopImages']\").val() != \"\" && $(\"#\" + nodeId).val() == \"\") {\r\n");
      out.write("            return true;\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"请上传图片！\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $('#side-menu').siblings().removeClass('active');\r\n");
      out.write("    $('#image_Menu').addClass('active');\r\n");
      out.write("    $('#image_manage_Menu').addClass('active');\r\n");
      out.write("    $('#image_manage_Menu1 ').addClass('active');\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /static/common/taglibs.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctxBOSS");
      // /static/common/taglibs.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/static/common/taglibs.jsp(14,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /static/common/taglibs.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ctx");
      // /static/common/taglibs.jsp(15,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/static/common/taglibs.jsp(15,0) '${pageContext.request.contextPath}/static'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}/static",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /static/common/taglibs.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path");
      // /static/common/taglibs.jsp(16,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/static/common/taglibs.jsp(16,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/demo/testpaper/addNounTest.jsp(53,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest != null && nonuTest.cardColorRecord != null && nonuTest.cardColorRecord != ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <audio id=\"audio\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardColorRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \" controls></audio>\r\n");
          out.write("                                <br/>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/demo/testpaper/addNounTest.jsp(89,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest != null && nonuTest.cardWireRecord != null && nonuTest.cardWireRecord != ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <audio id=\"audio\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.cardWireRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \" controls></audio>\r\n");
          out.write("                                <br/>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/jsp/demo/testpaper/addNounTest.jsp(126,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest != null && nonuTest.groupRecord != null && nonuTest.groupRecord != ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                <audio id=\"audio\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nonuTest.groupRecord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \" controls></audio>\r\n");
          out.write("                                <br/>\r\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
