/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-03-28 03:39:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.demo.questionnaire;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pcdiAndabcResultList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/tld/general.tld", Long.valueOf(1538117498787L));
    _jspx_dependants.put("/WEB-INF/jsp/demo/public/menu.jsp", Long.valueOf(1552027385318L));
    _jspx_dependants.put("/static/common/taglibs.jsp", Long.valueOf(1541399470113L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1532604868850L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/jsp/demo/public/headCssJs.jsp", Long.valueOf(1545295123769L));
    _jspx_dependants.put("/WEB-INF/jsp/demo/public/pageTop.jsp", Long.valueOf(1542961855154L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>问卷记录列表</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap-switch.css\"  rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/currency.css\">\r\n");
      out.write("    <link href=\"/static/css/pcdiRequired.css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/font-awesome/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/toastr/toastr.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/gritter/jquery.gritter.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/dataTables/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/dataTables/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/dataTables/dataTables.tableTools.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/plugins/datapicker/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap-switch.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/metisMenu/jquery.metisMenu.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/inspinia.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/slimscroll/jquery.slimscroll.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/pace/pace.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-ui-1.10.4.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-migrate-1.1.0.min.js\"  type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/jquery.dataTables.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/dataTables.bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/dataTables.responsive.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/dataTables/dataTables.tableTools.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/datapicker/Moment.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/datapicker/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/jsTree/jstree.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/plugins/chosen/chosen.jquery.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/layer/layer.js\"></script>\r\n");
      out.write("    <!-- 页面的js列表 -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sha1.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.ajaxfileupload.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    function switchChange(data){\r\n");
      out.write("\r\n");
      out.write("        alert(data);\r\n");
      out.write("    }\r\n");
      out.write("    function getSwitch(data,id){\r\n");
      out.write("        var ret=\"\";\r\n");
      out.write("        if(data==0){\r\n");
      out.write("            ret='<div class=\"switch switch-mini\" id=\"switchId\" >'+'<input  value=\"0\" rowId='+id+' type=\"checkbox\" checked />'+'</div>';\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        if(data==1){\r\n");
      out.write("            ret='<div class=\"switch switch-mini\" id=\"switchId\" >'+'<input value=\"1\" rowId='+id+' type=\"checkbox\" />'+'</div>';\r\n");
      out.write("        }\r\n");
      out.write("        return ret;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /**\r\n");
      out.write("     * 时间戳转日期\r\n");
      out.write("     * @param timestamp\r\n");
      out.write("     * @returns {*}\r\n");
      out.write("     */\r\n");
      out.write("    function timestampToTime(timestamp) {\r\n");
      out.write("        var date = new Date(timestamp * 1000);//时间戳为10位需*1000，时间戳为13位的话不需乘1000\r\n");
      out.write("        Y = date.getFullYear() + '-';\r\n");
      out.write("        M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';\r\n");
      out.write("        D = date.getDate() + ' ';\r\n");
      out.write("        h = date.getHours() + ':';\r\n");
      out.write("        m = date.getMinutes() + ':';\r\n");
      out.write("        s = date.getSeconds();\r\n");
      out.write("        if(s < 10){\r\n");
      out.write("            s = \"0\"+s;\r\n");
      out.write("        }\r\n");
      out.write("        return Y+M+D+h+m+s;\r\n");
      out.write("    }\r\n");
      out.write("    /**\r\n");
      out.write("     * 时间戳转日期\r\n");
      out.write("     * @param timestamp\r\n");
      out.write("     * @returns {*}\r\n");
      out.write("     */\r\n");
      out.write("    function timestampToyyyy_MM_dd(timestamp) {\r\n");
      out.write("        var date = new Date(timestamp * 1000);//时间戳为10位需*1000，时间戳为13位的话不需乘1000\r\n");
      out.write("        Y = date.getFullYear() + '-';\r\n");
      out.write("        M = (date.getMonth()+1 < 10 ? '0'+(date.getMonth()+1) : date.getMonth()+1) + '-';\r\n");
      out.write("        D = date.getDate() + ' ';\r\n");
      out.write("        return Y+M+D;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .firstLevelMenu{\r\n");
      out.write("        font-size: medium;\r\n");
      out.write("    }\r\n");
      out.write("   #side-menu li{\r\n");
      out.write("        display: none;\r\n");
      out.write("        color: red;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("    <nav class=\"navbar-default navbar-static-side\" role=\"navigation\">\r\n");
      out.write("        <div class=\"sidebar-collapse\">\r\n");
      out.write("            <ul  class=\"nav metismenu\" id=\"side-menu1\">\r\n");
      out.write("                <li class=\"nav-header\">\r\n");
      out.write("                    <div class=\"dropdown profile-element\"> <span>\r\n");
      out.write("                            <img alt=\"image\" class=\"img-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/page/baidumarker.png\"/>\r\n");
      out.write("                             </span>\r\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                            <span class=\"clear\"> <span class=\"block m-t-xs\"> <strong class=\"font-bold\">管理人员</strong>\r\n");
      out.write("                             </span>  </span> </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"logo-element\">\r\n");
      out.write("                        <input  hidden id=\"thisUserid\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.get(\"user\").id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav metismenu\" id=\"side-menu\">\r\n");
      out.write("                <li id=\"workbench_menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >工作台</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"workbenchmenu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/workbench/toWorkBenchPage\">工作台</a></li>\r\n");
      out.write("                        <li id=\"workbenchmenu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/trainTest/toCoursewaretListPage\">课件统计</a></li>\r\n");
      out.write("                        <li id=\"workbenchmenu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/trainTest/touserDetailList\">用户详情统计</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"image_Menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >图片管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"image_manage_Menu\"><a href=\"\">名词图片管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNoumTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNoumTestPage\">测试</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/noun/toNounSensePage\">意义</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li id=\"image_manage_Menu11\"><a href=\"\">动词图片管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/verb/toVerbTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu4\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/verb/toVerbTestPage\">测试</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li id=\"image_manage_Menu12\"><a href=\"\">句子成组管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu5\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceGroupTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu6\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceGroupTestPage\">测试</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li id=\"image_manage_Menu13\"><a href=\"\">句子分解管理</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse hul\">\r\n");
      out.write("                                <li id=\"image_manage_Menu7\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceResolveTrainingPage\">训练</a></li>\r\n");
      out.write("                                <li id=\"image_manage_Menu8\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/sentence/toSentenceResolveTestPage\">测试</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"msq_Menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >问卷管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"msq_Menu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toPcdiList\">pcdi必做问卷</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toPcdiSelectList\">pcdi选做问卷</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toAbcListPage\">ABC问卷</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/topcdiAndabc/resultPage\">问卷记录</a></li>\r\n");
      out.write("                        <li id=\"msq_Menu4\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/toWordListPage\">建议设置</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"user_menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >人员管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"user_menu0\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/getAccountList\">账号管理</a></li>\r\n");
      out.write("                        <li id=\"user_menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roleAccess/toRoleListPage\">角色管理</a></li>\r\n");
      out.write("                        <li id=\"user_menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/user/toParentsPage\">用户管理</a></li>\r\n");
      out.write("                        <li id=\"user_menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/user/toChildPage\">儿童管理</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li id=\"system_menu\">\r\n");
      out.write("                    <a href=\"\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label firstLevelMenu\" >系统管理</span></span><span class=\"fa arrow\"></span> </a>\r\n");
      out.write("                    <ul class=\"nav nav-second-level collapse\">\r\n");
      out.write("                        <li id=\"system_menu1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toVersionPage\">版本日志</a></li>\r\n");
      out.write("                        <li id=\"system_menu2\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toStrartPage\">启动页</a></li>\r\n");
      out.write("                        <li id=\"system_menu3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toIntroduceList\">产品介绍</a></li>\r\n");
      out.write("                        <li id=\"system_menu4\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/system/toSuggestPage\">信息设置</a></li>\r\n");
      out.write("                        <li id=\"system_menu5\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/city/toCityList\">地区设置</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function (){\r\n");
      out.write("        var  id= $(\"#thisUserid\").val();\r\n");
      out.write("       var AccessList = '';\r\n");
      out.write("        //获取该用户的权限\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/getUserAccessList\",\r\n");
      out.write("            data:{id:id},\r\n");
      out.write("            dataType: 'JSON',\r\n");
      out.write("            type:\"POST\",\r\n");
      out.write("            success: function (result) {\r\n");
      out.write("                console.log(result);\r\n");
      out.write("                if (result.code == 200) {\r\n");
      out.write("                    var list = result.data;\r\n");
      out.write("                    for(var i = 0; i< list.length; i++){\r\n");
      out.write("                        if (list[i].access != null){\r\n");
      out.write("                            $(\"#\"+list[i].access).css(\"display\",\"block\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }else {\r\n");
      out.write("                    alert(result.msg);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // init vConsole\r\n");
      out.write("   /* var vConsole = new VConsole();\r\n");
      out.write("    console.log('Hello world');*/\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper animated fadeInRight gray-bg\">\r\n");
      out.write("    <div class=\"row border-bottom\">\r\n");
      out.write("        <nav class=\"navbar navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a id=\"user\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/toindexPage\">\r\n");
      out.write("                        <input  hidden id=\"accountId\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.get(\"user\").id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        <i class=\"fa fa-user\" ></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.get(\"user\").accountName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a id=\"updatePassword\">\r\n");
      out.write("                        <i class=\"fa fa-key\" ></i>修改密码\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/loginOut\">\r\n");
      out.write("                        <i class=\"fa fa-sign-out\"></i> 退出\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"exampleModalLabel\">修改密码</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"control-label\">旧密码:</label>\r\n");
      out.write("\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"oldPassword\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label  class=\"control-label\">新密码:</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"newPassword1\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label  class=\"control-label\">确认密码:</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"newPassword2\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-success\" id=\"updatePasswordBtn\">确定</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(\"#updatePassword\").click(function () {\r\n");
      out.write("        $(\"#exampleModal\").modal('show');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("        $(\"#updatePasswordBtn\").click(function(){\r\n");
      out.write("            var oldPassword=$(\"#oldPassword\").val();\r\n");
      out.write("            var newPassword1=$(\"#newPassword1\").val();\r\n");
      out.write("            var newPassword2 =$(\"#newPassword2\").val();\r\n");
      out.write("            if(oldPassword==\"\"||oldPassword==null||oldPassword==\"undefined\"){\r\n");
      out.write("            alert(\"请填写旧密码！\");\r\n");
      out.write("            return;\r\n");
      out.write("            }\r\n");
      out.write("            if(newPassword1==\"\"||newPassword1==null||newPassword1==\"undefined\"){\r\n");
      out.write("                alert(\"请填写新密码！\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if(newPassword2==\"\"||newPassword2==null||newPassword2==\"undefined\"){\r\n");
      out.write("                alert(\"请填写确认密码！\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if(newPassword1 != newPassword2){\r\n");
      out.write("                alert(\"新密码和确认密码不相同！\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/updatePassword\",\r\n");
      out.write("                type: 'POST',\r\n");
      out.write("                dataType:'json',\r\n");
      out.write("                data: {\r\n");
      out.write("                    \"oldPassword\":oldPassword,\r\n");
      out.write("                    \"newPassword\":newPassword1,\r\n");
      out.write("                    \"accountId\":$(\"#accountId\").val()\r\n");
      out.write("                },\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("                    console.log(data);\r\n");
      out.write("                    if (data.code == 200) {\r\n");
      out.write("                        $(\"#exampleModal\").modal('hide');\r\n");
      out.write("                        alert(data.msg);\r\n");
      out.write("                        window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/loginOut\";\r\n");
      out.write("                    }else{\r\n");
      out.write("                        alert(data.msg);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("    <div id=\"page-wrapper\" class=\"gray-bg\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\" style=\"margin-left: 10px;margin-top: 20px;\">\r\n");
      out.write("                <div style=\"line-height: 34px;display: inline-block;\">\r\n");
      out.write("                    <label>昵&nbsp;&nbsp;称</label>\r\n");
      out.write("                    <div style=\"width: 200px;display: inline-block;margin: 0px 50px 0px 10px;\">\r\n");
      out.write("                        <input class=\"form-control\" type=\"text\" id=\"name\" name=\"name\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"line-height: 34px;display: inline-block;\">\r\n");
      out.write("                    <label>性&nbsp;&nbsp;别</label>\r\n");
      out.write("                    <div style=\"width: 200px;display: inline-block;margin: 0px 50px 0px 10px;\">\r\n");
      out.write("                        <select id=\"sex\" class=\"form-control\" name=\"sex\">\r\n");
      out.write("                            <option value=\"\">全部</option>\r\n");
      out.write("                            <option value=\"0\">男</option>\r\n");
      out.write("                            <option value=\"1\">女</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"line-height: 34px;display: inline-block;\">\r\n");
      out.write("                    <label>家长手机号</label>\r\n");
      out.write("                    <div style=\"width: 200px;display: inline-block;margin: 0px 50px 0px 10px;\">\r\n");
      out.write("                        <input class=\"form-control\" type=\"text\" id=\"phone\" name=\"phone\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"line-height: 34px;display: inline-block;\">\r\n");
      out.write("                    <label>出生日期</label>\r\n");
      out.write("                    <div id=\"data_1\" style=\"width: 210px;display: inline-block;margin: 0px 50px 0px 10px;vertical-align: top;\">\r\n");
      out.write("                        <div class='input-group date' id='datetimepicker1'>\r\n");
      out.write("                            <input type='text' class=\"form-control\" id=\"birthdate\"  />\r\n");
      out.write("                            <span class=\"input-group-addon\">\r\n");
      out.write("                        <span class=\"glyphicon glyphicon-calendar\"></span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"display: inline-block;margin-left: 20px;\">\r\n");
      out.write("                    <button class=\"btn btn-success bt-search\">查询</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\" style=\"margin-left: 10px;margin-top: 20px;\">\r\n");
      out.write("                <div style=\"line-height: 34px;display: inline-block;\">\r\n");
      out.write("                    <label>问卷类型</label>\r\n");
      out.write("                    <div style=\"width: 200px;display: inline-block;margin: 0px 50px 0px 10px;\">\r\n");
      out.write("                        <select id=\"type\" class=\"form-control\" name=\"type\">\r\n");
      out.write("                            <option value=\"\">请选择</option>\r\n");
      out.write("                            <option value=\"1\">PCDI必填</option>\r\n");
      out.write("                            <option value=\"2\">PCDI全部</option>\r\n");
      out.write("                            <option value=\"3\">ABC问卷</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"line-height: 34px;display: inline-block;\">\r\n");
      out.write("                    <label>是否有效</label>\r\n");
      out.write("                    <div style=\"width: 200px;display: inline-block;margin: 0px 50px 0px 10px;\">\r\n");
      out.write("                        <select id=\"valid\" class=\"form-control\" name=\"valid\">\r\n");
      out.write("                            <option value=\"\">请选择</option>\r\n");
      out.write("                            <option value=\"1\">有效</option>\r\n");
      out.write("                            <option value=\"2\">无效</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"wrapper wrapper-content animated fadeInRight\">\r\n");
      out.write("            <table class=\"table table-striped table-bordered table-hover dataTables-example\" id=\"data-table\" >\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"deleteCarouselFigure\" class=\"modal fade \" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("     aria-labelledby=\"mySmallModalLabel\">\r\n");
      out.write("    <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span\r\n");
      out.write("                        aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("                <h4 class=\"modal-title\">提示</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <p>您确定要删除吗？</p>\r\n");
      out.write("                <input id=\"deleteId\" type=\"hidden\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <a href=\"javascript:;\" class=\"btn btn-sm btn-white\" data-dismiss=\"modal\">关闭</a>\r\n");
      out.write("                <button id=\"ok\" class=\"btn btn-sm btn-success\">确定</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script >\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        var type ;\r\n");
      out.write("        var name ;\r\n");
      out.write("        var sex  ;\r\n");
      out.write("        var phone ;\r\n");
      out.write("        var birthdate ;\r\n");
      out.write("        var valid ;\r\n");
      out.write("        var conf_dt = {\r\n");
      out.write("            paging: true,//分页\r\n");
      out.write("            ordering: false,//是否启用排序\r\n");
      out.write("            searching: false,//搜索\r\n");
      out.write("            //lengthMenu: [25, 50],\r\n");
      out.write("            scrollX: \"100%\",\r\n");
      out.write("            displayLength: 10,\r\n");
      out.write("            language: {\r\n");
      out.write("                lengthMenu: '<div class=\"dataTables_length\" id=\"data-table_length\"><label>展示<select name=\"data-table_length\" aria-controls=\"data-table\" class=\"\">'+'<option value=\"10\">10</option>'  + '<option value=\"20\">20</option>' + '<option value=\"30\">30</option>' + '<option value=\"100\">100</option>'+'</select>条记录</laber></div></div>',\r\n");
      out.write("//                + '<button class=\"sendEmail btn btn-success\" style=\"margin-left: 10px\">发送邮件</button></div>',\r\n");
      out.write("                search: '<span class=\"label label-success\"></span>',//右上角的搜索文本，可以写html标签\r\n");
      out.write("                paginate: {//分页的样式内容。\r\n");
      out.write("                    previous: \"上一页\",\r\n");
      out.write("                    next: \"下一页\",\r\n");
      out.write("                    first: \"第一页\",\r\n");
      out.write("                    last: \"最后\"\r\n");
      out.write("                },\r\n");
      out.write("                zeroRecords: \"没有内容\",//table tbody内容为空时，tbody的内容。\r\n");
      out.write("                //下面三者构成了总体的左下角的内容。\r\n");
      out.write("                info: \"总共_PAGES_ 页，显示第_START_ 到第 _END_ ，筛选之后得到 _TOTAL_ 条，初始_MAX_ 条 \",//左下角的信息显示，大写的词为关键字。\r\n");
      out.write("                infoEmpty: \"0条记录\",//筛选为空时左下角的显示。\r\n");
      out.write("                infoFiltered: \"\",//筛选之后的左下角筛选提示，\r\n");
      out.write("            },\r\n");
      out.write("            paging: true,\r\n");
      out.write("            pagingType: \"full_numbers\",//分页样式的类型\r\n");
      out.write("            columns: [\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"ID\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"id\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"id\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"昵称\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"name\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"name\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"性别\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"sex\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"sex\",\r\n");
      out.write("                    \"render\": function (data, type, full, meta) {\r\n");
      out.write("                        if (data == \"1\"){\r\n");
      out.write("                            return \"女\";\r\n");
      out.write("                        }else {\r\n");
      out.write("                            return \"男\"\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"出生日期\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"birthDate\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"birthDate\",\r\n");
      out.write("                    \"render\": function (data, type, full, meta) {\r\n");
      out.write("                        return timestampToyyyy_MM_dd(data/1000);\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"家长手机号\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"phone\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"phone\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"问卷类型\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"type\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"type\",\r\n");
      out.write("                    \"render\": function (data, type, full, meta) {\r\n");
      out.write("                        if (data == \"3\"){\r\n");
      out.write("                            return \"ABC问卷\";\r\n");
      out.write("                        }else {\r\n");
      out.write("                            return \"PCDI问卷\"\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"是否有效\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"isValid\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"isValid\",\r\n");
      out.write("                    \"render\": function (data, type, full, meta) {\r\n");
      out.write("                        if (data == \"1\"){\r\n");
      out.write("                            return \"有效\";\r\n");
      out.write("                        }\r\n");
      out.write("                        if(data == \"2\"){\r\n");
      out.write("                            return \"无效\"\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"总分\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"score\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"score\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"答题时间\",\r\n");
      out.write("                    \"type\": \"html\",\r\n");
      out.write("                    \"data\": \"createTime\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"createTime\",\r\n");
      out.write("                    \"render\": function (data, type, full, meta) {\r\n");
      out.write("                        return timestampToTime(data/1000);\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    \"title\": \"操作\",\r\n");
      out.write("                    \"type\": \"num\",\r\n");
      out.write("                    \"data\": \"id\",\r\n");
      out.write("                    \"defaultContent\": \"\",\r\n");
      out.write("                    \"name\": \"id\",\r\n");
      out.write("                    \"render\": function (data, type, full, meta) {\r\n");
      out.write("                        var ret = '<button style=\"margin-right: 5px;\" class=\" btn btn-success btn-xs   btn-resultInfo\" id=\"' + data +\r\n");
      out.write("                            '\">修改</button>'+\r\n");
      out.write("                            '<button style=\"margin-right: 5px;\" class=\" btn btn-success btn-xs   btn-info\" id=\"' + data +\r\n");
      out.write("                            '\">查看问卷</button>';\r\n");
      out.write("                        return ret;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            ],\r\n");
      out.write("            serverSide: true,\r\n");
      out.write("            ajax: {\r\n");
      out.write("                \"url\": \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/getresultList.ajax\",\r\n");
      out.write("                \"data\": function (d) {\r\n");
      out.write("                    d.type = type;\r\n");
      out.write("                    d.name = name;\r\n");
      out.write("                    d.phone = phone;\r\n");
      out.write("                    d.sex = sex;\r\n");
      out.write("                    d.valid = valid;\r\n");
      out.write("                    d.birthdate = birthdate;\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            \"fnDrawCallback\":function(obj){\r\n");
      out.write("                $('#switchId input').bootstrapSwitch({onText:'正常',offText:'冻结',onSwitchChange:function(){\r\n");
      out.write("                    var switch_status=$(this).val();\r\n");
      out.write("                    var rowId=$(this).attr(\"rowId\");\r\n");
      out.write("                    if(switch_status==0){//正常 变冻结\r\n");
      out.write("                        updateStatus(rowId,1);\r\n");
      out.write("                    }\r\n");
      out.write("                    if(switch_status==1){//冻结 变正常\r\n");
      out.write("                        updateStatus(rowId,0);\r\n");
      out.write("                    }\r\n");
      out.write("                } });\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            index: 0\r\n");
      out.write("        };\r\n");
      out.write("        var $dataTable = $('#data-table').dataTable(conf_dt);\r\n");
      out.write("        var id;\r\n");
      out.write("        //查看问卷\r\n");
      out.write("        $dataTable.on('click',\".btn-info\",function () {\r\n");
      out.write("            id= $(this).attr(\"id\");\r\n");
      out.write("            window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/topcdiAndabc/resultInfo?id=\"+id;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        //文案查看\r\n");
      out.write("        $dataTable.on('click',\".btn-resultInfo\",function () {\r\n");
      out.write("            id= $(this).attr(\"id\");\r\n");
      out.write("            window.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/roll/topcdiAndabc/adviceInfo?resultId=\"+id;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.bt-search').click(function () {\r\n");
      out.write("            type=$(\"#type\").val();\r\n");
      out.write("            name=$(\"#name\").val();\r\n");
      out.write("            phone=$(\"#phone\").val();\r\n");
      out.write("            sex=$(\"#sex\").val();\r\n");
      out.write("            valid=$(\"#valid\").val();\r\n");
      out.write("            birthdate=$(\"#birthdate\").val();\r\n");
      out.write("            $dataTable.fnDraw();\r\n");
      out.write("        });\r\n");
      out.write("        //时间选择器\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $('#datetimepicker1').datetimepicker({\r\n");
      out.write("                format: 'YYYY-MM-DD'\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        function updateStatus(id,status) {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/account/updateStatus\",\r\n");
      out.write("                dataType:'JSON',\r\n");
      out.write("                data:{\r\n");
      out.write("                    id:id,\r\n");
      out.write("                    status:status\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    console.log(response);\r\n");
      out.write("                    if (response == 200) {\r\n");
      out.write("                        $dataTable.fnDraw();\r\n");
      out.write("                    }else{\r\n");
      out.write("                        alert(\"出现异常！\");\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('#side-menu').siblings().removeClass('active');\r\n");
      out.write("    $('#msq_Menu').addClass('active');\r\n");
      out.write("    $('#msq_Menu3').addClass('active');\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /static/common/taglibs.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctxBOSS");
      // /static/common/taglibs.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/static/common/taglibs.jsp(14,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /static/common/taglibs.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ctx");
      // /static/common/taglibs.jsp(15,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/static/common/taglibs.jsp(15,0) '${pageContext.request.contextPath}/static'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}/static",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /static/common/taglibs.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path");
      // /static/common/taglibs.jsp(16,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/static/common/taglibs.jsp(16,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
